# Generated by Django 4.0.6 on 2022-07-31 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='static/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_type',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='products.quantityvariant'),
        ),
    ]
